"""empty message

Revision ID: 330c50cb4916
Revises: d174c82ff162
Create Date: 2021-04-21 20:46:47.616732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330c50cb4916'
down_revision = 'd174c82ff162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_field', table_name='item')
    op.create_index('ix_post_tags', 'item', ['description'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_tags', table_name='item')
    op.create_index('index_field', 'item', ['title', 'description'], unique=False)
    # ### end Alembic commands ###
