"""empty message

Revision ID: d174c82ff162
Revises: 
Create Date: 2021-04-21 20:07:43.218777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd174c82ff162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_idx')
    op.create_index('index_field', 'item', ['title', 'description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_field', table_name='item')
    op.create_table('item_idx',
    sa.Column('rowid', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('rowid')
    )
    # ### end Alembic commands ###
